<?php

namespace Javaabu\Cms\Enums;

use Javaabu\Helpers\Enums\IsEnum;
use Javaabu\Helpers\Enums\NativeEnumsTrait;

enum Flags: string implements IsEnum
{
    use NativeEnumsTrait;

    // Enum cases
    case AD = 'ad';
    case AE = 'ae';
    case AF = 'af';
    case AG = 'ag';
    case AI = 'ai';
    case AL = 'al';
    case AM = 'am';
    case AN = 'an';
    case AO = 'ao';
    case AR = 'ar';
    case AS = 'as';
    case AT = 'at';
    case AU = 'au';
    case AW = 'aw';
    case AX = 'ax';
    case AZ = 'az';
    case BA = 'ba';
    case BB = 'bb';
    case BD = 'bd';
    case BE = 'be';
    case BF = 'bf';
    case BG = 'bg';
    case BH = 'bh';
    case BI = 'bi';
    case BJ = 'bj';
    case BM = 'bm';
    case BN = 'bn';
    case BO = 'bo';
    case BR = 'br';
    case BS = 'bs';
    case BT = 'bt';
    case BV = 'bv';
    case BW = 'bw';
    case BY = 'by';
    case BZ = 'bz';
    case CA = 'ca';
    case CATALONIA = 'catalonia';
    case CC = 'cc';
    case CD = 'cd';
    case CF = 'cf';
    case CG = 'cg';
    case CH = 'ch';
    case CI = 'ci';
    case CK = 'ck';
    case CL = 'cl';
    case CM = 'cm';
    case CN = 'cn';
    case CO = 'co';
    case CR = 'cr';
    case CS = 'cs';
    case CU = 'cu';
    case CV = 'cv';
    case CX = 'cx';
    case CY = 'cy';
    case CZ = 'cz';
    case DE = 'de';
    case DJ = 'dj';
    case DK = 'dk';
    case DM = 'dm';
    case DO = 'do';
    case DZ = 'dz';
    case EC = 'ec';
    case EE = 'ee';
    case EG = 'eg';
    case EH = 'eh';
    case ENGLAND = 'england';
    case ER = 'er';
    case ES = 'es';
    case ET = 'et';
    case EUROPEANUNION = 'europeanunion';
    case FAM = 'fam';
    case FI = 'fi';
    case FJ = 'fj';
    case FK = 'fk';
    case FM = 'fm';
    case FO = 'fo';
    case FR = 'fr';
    case GA = 'ga';
    case GB = 'gb';
    case GD = 'gd';
    case GE = 'ge';
    case GF = 'gf';
    case GH = 'gh';
    case GI = 'gi';
    case GL = 'gl';
    case GM = 'gm';
    case GN = 'gn';
    case GP = 'gp';
    case GQ = 'gq';
    case GR = 'gr';
    case GS = 'gs';
    case GT = 'gt';
    case GU = 'gu';
    case GW = 'gw';
    case GY = 'gy';
    case HK = 'hk';
    case HM = 'hm';
    case HN = 'hn';
    case HR = 'hr';
    case HT = 'ht';
    case HU = 'hu';
    case ID = 'id';
    case IE = 'ie';
    case IL = 'il';
    case IN = 'in';
    case IO = 'io';
    case IQ = 'iq';
    case IR = 'ir';
    case IS = 'is';
    case IT = 'it';
    case JM = 'jm';
    case JO = 'jo';
    case JP = 'jp';
    case KE = 'ke';
    case KG = 'kg';
    case KH = 'kh';
    case KI = 'ki';
    case KM = 'km';
    case KN = 'kn';
    case KP = 'kp';
    case KR = 'kr';
    case KW = 'kw';
    case KY = 'ky';
    case KZ = 'kz';
    case LA = 'la';
    case LB = 'lb';
    case LC = 'lc';
    case LI = 'li';
    case LK = 'lk';
    case LR = 'lr';
    case LS = 'ls';
    case LT = 'lt';
    case LU = 'lu';
    case LV = 'lv';
    case LY = 'ly';
    case MA = 'ma';
    case MC = 'mc';
    case MD = 'md';
    case ME = 'me';
    case MG = 'mg';
    case MH = 'mh';
    case MK = 'mk';
    case ML = 'ml';
    case MM = 'mm';
    case MN = 'mn';
    case MO = 'mo';
    case MP = 'mp';
    case MQ = 'mq';
    case MR = 'mr';
    case MS = 'ms';
    case MT = 'mt';
    case MU = 'mu';
    case MV = 'mv';
    case MW = 'mw';
    case MX = 'mx';
    case MY = 'my';
    case MZ = 'mz';
    case NA = 'na';
    case NC = 'nc';
    case NE = 'ne';
    case NF = 'nf';
    case NG = 'ng';
    case NI = 'ni';
    case NL = 'nl';
    case NO = 'no';
    case NP = 'np';
    case NR = 'nr';
    case NU = 'nu';
    case NZ = 'nz';
    case OM = 'om';
    case PA = 'pa';
    case PE = 'pe';
    case PF = 'pf';
    case PG = 'pg';
    case PH = 'ph';
    case PK = 'pk';
    case PL = 'pl';
    case PM = 'pm';
    case PN = 'pn';
    case PR = 'pr';
    case PS = 'ps';
    case PT = 'pt';
    case PW = 'pw';
    case PY = 'py';
    case QA = 'qa';
    case RE = 're';
    case RO = 'ro';
    case RS = 'rs';
    case RU = 'ru';
    case RW = 'rw';
    case SA = 'sa';
    case SB = 'sb';
    case SC = 'sc';
    case SCOTLAND = 'scotland';
    case SD = 'sd';
    case SE = 'se';
    case SG = 'sg';
    case SH = 'sh';
    case SI = 'si';
    case SJ = 'sj';
    case SK = 'sk';
    case SL = 'sl';
    case SM = 'sm';
    case SN = 'sn';
    case SO = 'so';
    case SR = 'sr';
    case ST = 'st';
    case SV = 'sv';
    case SY = 'sy';
    case SZ = 'sz';
    case TC = 'tc';
    case TD = 'td';
    case TF = 'tf';
    case TG = 'tg';
    case TH = 'th';
    case TJ = 'tj';
    case TK = 'tk';
    case TL = 'tl';
    case TM = 'tm';
    case TN = 'tn';
    case TO = 'to';
    case TR = 'tr';
    case TT = 'tt';
    case TV = 'tv';
    case TW = 'tw';
    case TZ = 'tz';
    case UA = 'ua';
    case UG = 'ug';
    case UM = 'um';
    case US = 'us';
    case UY = 'uy';
    case UZ = 'uz';
    case VA = 'va';
    case VC = 'vc';
    case VE = 've';
    case VG = 'vg';
    case VI = 'vi';
    case VN = 'vn';
    case VU = 'vu';
    case WALES = 'wales';
    case WF = 'wf';
    case WS = 'ws';
    case YE = 'ye';
    case YT = 'yt';
    case ZA = 'za';
    case ZM = 'zm';
    case ZW = 'zw';

    public static function labels(): array
    {
        return [
            self::AD->value            => __("Andorra"),
            self::AE->value            => __("United Arab Emirates"),
            self::AF->value            => __("Afghanistan"),
            self::AG->value            => __("Antigua and Barbuda"),
            self::AI->value            => __("Anguilla"),
            self::AL->value            => __("Albania"),
            self::AM->value            => __("Armenia"),
            self::AN->value            => __("Netherlands Antilles"),
            self::AO->value            => __("Angola"),
            self::AR->value            => __("Argentina"),
            self::AS->value            => __("American Samoa"),
            self::AT->value            => __("Austria"),
            self::AU->value            => __("Australia"),
            self::AW->value            => __("Aruba"),
            self::AX->value            => __("Åland Islands"),
            self::AZ->value            => __("Azerbaijan"),
            self::BA->value            => __("Bosnia and Herzegovina"),
            self::BB->value            => __("Barbados"),
            self::BD->value            => __("Bangladesh"),
            self::BE->value            => __("Belgium"),
            self::BF->value            => __("Burkina Faso"),
            self::BG->value            => __("Bulgaria"),
            self::BH->value            => __("Bahrain"),
            self::BI->value            => __("Burundi"),
            self::BJ->value            => __("Benin"),
            self::BM->value            => __("Bermuda"),
            self::BN->value            => __("Brunei Darussalam"),
            self::BO->value            => __("Bolivia"),
            self::BR->value            => __("Brazil"),
            self::BS->value            => __("Bahamas"),
            self::BT->value            => __("Bhutan"),
            self::BV->value            => __("Bouvet Island"),
            self::BW->value            => __("Botswana"),
            self::BY->value            => __("Belarus"),
            self::BZ->value            => __("Belize"),
            self::CA->value            => __("Canada"),
            self::CATALONIA->value     => __("Catalonia"),
            self::CC->value            => __("Cocos (Keeling) Islands"),
            self::CD->value            => __("Congo, Democratic Republic of the"),
            self::CF->value            => __("Central African Republic"),
            self::CG->value            => __("Congo"),
            self::CH->value            => __("Switzerland"),
            self::CI->value            => __("Côte d'Ivoire"),
            self::CK->value            => __("Cook Islands"),
            self::CL->value            => __("Chile"),
            self::CM->value            => __("Cameroon"),
            self::CN->value            => __("China"),
            self::CO->value            => __("Colombia"),
            self::CR->value            => __("Costa Rica"),
            self::CS->value            => __("Serbia and Montenegro"),
            self::CU->value            => __("Cuba"),
            self::CV->value            => __("Cape Verde"),
            self::CX->value            => __("Christmas Island"),
            self::CY->value            => __("Cyprus"),
            self::CZ->value            => __("Czech Republic"),
            self::DE->value            => __("Germany"),
            self::DJ->value            => __("Djibouti"),
            self::DK->value            => __("Denmark"),
            self::DM->value            => __("Dominica"),
            self::DO->value            => __("Dominican Republic"),
            self::DZ->value            => __("Algeria"),
            self::EC->value            => __("Ecuador"),
            self::EE->value            => __("Estonia"),
            self::EG->value            => __("Egypt"),
            self::EH->value            => __("Western Sahara"),
            self::ENGLAND->value       => __("England"),
            self::ER->value            => __("Eritrea"),
            self::ES->value            => __("Spain"),
            self::ET->value            => __("Ethiopia"),
            self::EUROPEANUNION->value => __("European Union"),
            self::FAM->value           => __("Families"),
            self::FI->value            => __("Finland"),
            self::FJ->value            => __("Fiji"),
            self::FK->value            => __("Falkland Islands (Malvinas)"),
            self::FM->value            => __("Micronesia, Federated States of"),
            self::FO->value            => __("Faroe Islands"),
            self::FR->value            => __("France"),
            self::GA->value            => __("Gabon"),
            self::GB->value            => __("United Kingdom"),
            self::GD->value            => __("Grenada"),
            self::GE->value            => __("Georgia"),
            self::GF->value            => __("French Guiana"),
            self::GH->value            => __("Ghana"),
            self::GI->value            => __("Gibraltar"),
            self::GL->value            => __("Greenland"),
            self::GM->value            => __("Gambia"),
            self::GN->value            => __("Guinea"),
            self::GP->value            => __("Guadeloupe"),
            self::GQ->value            => __("Equatorial Guinea"),
            self::GR->value            => __("Greece"),
            self::GS->value            => __("South Georgia and the South Sandwich Islands"),
            self::GT->value            => __("Guatemala"),
            self::GU->value            => __("Guam"),
            self::GW->value            => __("Guinea-Bissau"),
            self::GY->value            => __("Guyana"),
            self::HK->value            => __("Hong Kong"),
            self::HM->value            => __("Heard Island and McDonald Islands"),
            self::HN->value            => __("Honduras"),
            self::HR->value            => __("Croatia"),
            self::HT->value            => __("Haiti"),
            self::HU->value            => __("Hungary"),
            self::ID->value            => __("Indonesia"),
            self::IE->value            => __("Ireland"),
            self::IL->value            => __("Israel"),
            self::IN->value            => __("India"),
            self::IO->value            => __("British Indian Ocean Territory"),
            self::IQ->value            => __("Iraq"),
            self::IR->value            => __("Iran, Islamic Republic of"),
            self::IS->value            => __("Iceland"),
            self::IT->value            => __("Italy"),
            self::JM->value            => __("Jamaica"),
            self::JO->value            => __("Jordan"),
            self::JP->value            => __("Japan"),
            self::KE->value            => __("Kenya"),
            self::KG->value            => __("Kyrgyzstan"),
            self::KH->value            => __("Cambodia"),
            self::KI->value            => __("Kiribati"),
            self::KM->value            => __("Comoros"),
            self::KN->value            => __("Saint Kitts and Nevis"),
            self::KP->value            => __("North Korea"),
            self::KR->value            => __("South Korea"),
            self::KW->value            => __("Kuwait"),
            self::KY->value            => __("Cayman Islands"),
            self::KZ->value            => __("Kazakhstan"),
            self::LA->value            => __("Lao People's Democratic Republic"),
            self::LB->value            => __("Lebanon"),
            self::LC->value            => __("Saint Lucia"),
            self::LI->value            => __("Liechtenstein"),
            self::LK->value            => __("Sri Lanka"),
            self::LR->value            => __("Liberia"),
            self::LS->value            => __("Lesotho"),
            self::LT->value            => __("Lithuania"),
            self::LU->value            => __("Luxembourg"),
            self::LV->value            => __("Latvia"),
            self::LY->value            => __("Libya"),
            self::MA->value            => __("Morocco"),
            self::MC->value            => __("Monaco"),
            self::MD->value            => __("Moldova"),
            self::ME->value            => __("Montenegro"),
            self::MG->value            => __("Madagascar"),
            self::MH->value            => __("Marshall Islands"),
            self::MK->value            => __("North Macedonia"),
            self::ML->value            => __("Mali"),
            self::MM->value            => __("Myanmar"),
            self::MN->value            => __("Mongolia"),
            self::MO->value            => __("Macao"),
            self::MP->value            => __("Northern Mariana Islands"),
            self::MQ->value            => __("Martinique"),
            self::MR->value            => __("Mauritania"),
            self::MS->value            => __("Montserrat"),
            self::MT->value            => __("Malta"),
            self::MU->value            => __("Mauritius"),
            self::MV->value            => __("Maldives"),
            self::MW->value            => __("Malawi"),
            self::MX->value            => __("Mexico"),
            self::MY->value            => __("Malaysia"),
            self::MZ->value            => __("Mozambique"),
            self::NA->value            => __("Namibia"),
            self::NC->value            => __("New Caledonia"),
            self::NE->value            => __("Niger"),
            self::NF->value            => __("Norfolk Island"),
            self::NG->value            => __("Nigeria"),
            self::NI->value            => __("Nicaragua"),
            self::NL->value            => __("Netherlands"),
            self::NO->value            => __("Norway"),
            self::NP->value            => __("Nepal"),
            self::NR->value            => __("Nauru"),
            self::NU->value            => __("Niue"),
            self::NZ->value            => __("New Zealand"),
            self::OM->value            => __("Oman"),
            self::PA->value            => __("Panama"),
            self::PE->value            => __("Peru"),
            self::PF->value            => __("French Polynesia"),
            self::PG->value            => __("Papua New Guinea"),
            self::PH->value            => __("Philippines"),
            self::PK->value            => __("Pakistan"),
            self::PL->value            => __("Poland"),
            self::PM->value            => __("Saint Pierre and Miquelon"),
            self::PN->value            => __("Pitcairn"),
            self::PR->value            => __("Puerto Rico"),
            self::PS->value            => __("Palestine"),
            self::PT->value            => __("Portugal"),
            self::PW->value            => __("Palau"),
            self::PY->value            => __("Paraguay"),
            self::QA->value            => __("Qatar"),
            self::RE->value            => __("Réunion"),
            self::RO->value            => __("Romania"),
            self::RS->value            => __("Serbia"),
            self::RU->value            => __("Russian Federation"),
            self::RW->value            => __("Rwanda"),
            self::SA->value            => __("Saudi Arabia"),
            self::SB->value            => __("Solomon Islands"),
            self::SC->value            => __("Seychelles"),
            self::SCOTLAND->value      => __("Scotland"),
            self::SD->value            => __("Sudan"),
            self::SE->value            => __("Sweden"),
            self::SG->value            => __("Singapore"),
            self::SH->value            => __("Saint Helena"),
            self::SI->value            => __("Slovenia"),
            self::SJ->value            => __("Svalbard and Jan Mayen"),
            self::SK->value            => __("Slovakia"),
            self::SL->value            => __("Sierra Leone"),
            self::SM->value            => __("San Marino"),
            self::SN->value            => __("Senegal"),
            self::SO->value            => __("Somalia"),
            self::SR->value            => __("Suriname"),
            self::ST->value            => __("Sao Tome and Principe"),
            self::SV->value            => __("El Salvador"),
            self::SY->value            => __("Syrian Arab Republic"),
            self::SZ->value            => __("Eswatini"),
            self::TC->value            => __("Turks and Caicos Islands"),
            self::TD->value            => __("Chad"),
            self::TF->value            => __("French Southern Territories"),
            self::TG->value            => __("Togo"),
            self::TH->value            => __("Thailand"),
            self::TJ->value            => __("Tajikistan"),
            self::TK->value            => __("Tokelau"),
            self::TL->value            => __("Timor-Leste"),
            self::TM->value            => __("Turkmenistan"),
            self::TN->value            => __("Tunisia"),
            self::TO->value            => __("Tonga"),
            self::TR->value            => __("Turkey"),
            self::TT->value            => __("Trinidad and Tobago"),
            self::TV->value            => __("Tuvalu"),
            self::TW->value            => __("Taiwan"),
            self::TZ->value            => __("Tanzania"),
            self::UA->value            => __("Ukraine"),
            self::UG->value            => __("Uganda"),
            self::UM->value            => __("United States Minor Outlying Islands"),
            self::US->value            => __("United States"),
            self::UY->value            => __("Uruguay"),
            self::UZ->value            => __("Uzbekistan"),
            self::VA->value            => __("Holy See (Vatican City State)"),
            self::VC->value            => __("Saint Vincent and the Grenadines"),
            self::VE->value            => __("Venezuela"),
            self::VG->value            => __("Virgin Islands, British"),
            self::VI->value            => __("Virgin Islands, U.S."),
            self::VN->value            => __("Vietnam"),
            self::VU->value            => __("Vanuatu"),
            self::WALES->value         => __("Wales"),
            self::WF->value            => __("Wallis and Futuna"),
            self::WS->value            => __("Samoa"),
            self::YE->value            => __("Yemen"),
            self::YT->value            => __("Mayotte"),
            self::ZA->value            => __("South Africa"),
            self::ZM->value            => __("Zambia"),
            self::ZW->value            => __("Zimbabwe"),
        ];
    }

    public static function listFlags(): array
    {
        $list = [];
        foreach (self::cases() as $case) {
            $list[$case->value] = [
                'image' => self::getFlagUrl($case->value),
                'code'  => $case->value,
                'name'  => __(self::labels()[$case->value]),
            ];
        }
        return $list;
    }

    public static function getFlagUrl(string $flag): string
    {
        return self::getFlagUrlPrefix() . $flag . self::getFlagUrlSuffix();
    }

    public static function getFlagUrlPrefix(): string
    {
        // Assuming 'asset' is a globally available function, otherwise adjust accordingly
        return asset('img/flags/') . '/';
    }

    public static function getFlagUrlSuffix(): string
    {
        return '.svg';
    }
}
